# Generated by Django 4.2.6 on 2024-07-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatinteraction_delete_chatbotinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatinteraction',
            old_name='message',
            new_name='bot_response',
        ),
        migrations.RenameField(
            model_name='chatinteraction',
            old_name='response',
            new_name='user_message',
        ),
    ]
