# Generated by Django 4.2.6 on 2024-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatbotsettings_assistant_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinteraction',
            name='bot_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatinteraction',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
